#!/bin/sh
# Shuts down after 3 seconds in a forked process.

# Completely detach this subshell: disconnect stdout, stderr, and stdin.
(sleep 3; sudo poweroff) </dev/null >/dev/null 2>&1 &
echo "Shutdown initiated..."

