#!/bin/sh

# Enter the ID of the 'micsnoop' device, as can be found in the output of `beepdetect.py -L`:
AUDIO_DEVICE=4

# If you run the PWM server on a different port, change it here:
SERVER_PORT=8081

SERVER_LOG=/var/log/pwm_server.log
DETECT_LOG=/var/log/beepdetect.log

# Move previous logs to /tmp so they can be inspected in case something went
# wrong last time. Moreover, this avoids overwriting the same inodes every time
# hence avoids wear problems on solid state disks.
[ -f "$SERVER_LOG" ] && mv -f "$SERVER_LOG" /tmp/old_pwm_server.log
[ -f "$DETECT_LOG" ] && mv -f "$DETECT_LOG" /tmp/old_beepdetect.log

su pi -c "nohup /usr/local/bin/pwm_server.py -p ${SERVER_PORT}" 2>&1 > $SERVER_LOG &
nohup nice -n -15 /usr/local/bin/beepdetect.py -D "${AUDIO_DEVICE}" -p "${SERVER_PORT}" 2>&1 > $DETECT_LOG &
